language: python

python:
- "3.6"

env:
- TOXENV=py27-d16
- TOXENV=py27-d17
- TOXENV=py34-d17
- TOXENV=py36-d17
- TOXENV=py38-d17
- TOXENV=cov

branches:
    only:
    - master
    - develop

install: pip install --quiet --use-mirrors tox

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install --quiet --use-mirrors coveralls;
    coveralls;
  fi
