language: python

python:
- "3.6"
- "3.7"
- "3.8"
- "3.9"

branches:
    only:
    - master
    - develop

install: pip install --quiet tox

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install --quiet coveralls;
    coveralls;
  fi
